// GENERATED BY loom. DO NOT EDIT.

import type Koa from "koa"
import { registerLoomRoutes } from "@loom/koa"
import { actionRegistry } from "../../../shared/generated/action-registry.generated.js"
import { queryRegistry } from "../../../shared/generated/query-registry.generated.js"
import { createRequestContext } from "./context.js"

export function registerGeneratedRoutes(app: Koa) {
  registerLoomRoutes(app, { actionRegistry, queryRegistry, createRequestContext })
}
