// GENERATED BY loomstack. DO NOT EDIT.

import type Koa from "koa"
import { registerLoomStackRoutes } from "@loomstack/koa"
import { actionRegistry } from "../../../shared/generated/action-registry.generated.js"
import { queryRegistry } from "../../../shared/generated/query-registry.generated.js"
import { createRequestContext } from "./context.js"

export function registerGeneratedRoutes(app: Koa) {
  registerLoomStackRoutes(app, { actionRegistry, queryRegistry, createRequestContext })
}
