import { mkdtempSync, readFileSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"
import { describe, expect, it } from "vitest"
import { scanProject } from "@loom/core"
import { createApp, createFeature, generateProject, renderGeneratedFiles } from "../src/index.js"

describe("generator", () => {
  it("creates a canonical app and feature without overwriting", () => {
    const parent = mkdtempSync(join(tmpdir(), "loom-generator-"))
    const app = createApp(parent, "demo-app")
    expect(app.createdFiles).toContain("apps/web/src/routes.generated.tsx")
    const feature = createFeature(app.root, "project-notes")
    expect(feature.createdFiles).toContain("features/project-notes/feature.yaml")
    expect(() => createFeature(app.root, "project-notes")).toThrow(/already exists/)
  })

  it("renders sorted deterministic registries and generated markers", () => {
    const parent = mkdtempSync(join(tmpdir(), "loom-generator-"))
    const { root } = createApp(parent, "demo")
    createFeature(root, "zebra")
    createFeature(root, "alpha")
    const scanned = scanProject(root)
    const first = renderGeneratedFiles(scanned.project!)
    const second = renderGeneratedFiles(scanned.project!)
    expect(first).toEqual(second)
    expect(first["shared/generated/feature-registry.generated.ts"]).toMatchInlineSnapshot(`
      "// GENERATED BY loom. DO NOT EDIT.

      export const featureRegistry = {
        \"alpha\": { id: \"alpha\", name: \"Alpha\", manifestPath: \"features/alpha/feature.yaml\" },
        \"zebra\": { id: \"zebra\", name: \"Zebra\", manifestPath: \"features/zebra/feature.yaml\" }
      } as const
      "
    `)
  })

  it("tracks generated files by content hash", () => {
    const parent = mkdtempSync(join(tmpdir(), "loom-generator-"))
    const { root } = createApp(parent, "demo")
    writeFileSync(join(root, "features/.gitkeep"), "still deterministic")
    const result = generateProject(root)
    const manifest = JSON.parse(readFileSync(join(root, ".loom/generated-files.json"), "utf8"))
    expect(result.generatedFiles).toContain(".loom/generated-files.json")
    expect(manifest.files).toEqual(expect.arrayContaining([expect.objectContaining({ path: ".loom/context.json", sha256: expect.stringMatching(/^[a-f0-9]{64}$/) })]))
  })
})
