// GENERATED BY loom. DO NOT EDIT.

import { createActionClient, createQueryClient } from "@loom/react"
import type { createCommitment as _createCommitmentDefinition } from "../../../features/commitments/actions/create-commitment.action.js"
import type { createPerson as _createPersonDefinition } from "../../../features/people/actions/create-person.action.js"
import type { createProject as _createProjectDefinition } from "../../../features/projects/actions/create-project.action.js"
import type { listCommitments as _listCommitmentsDefinition } from "../../../features/commitments/queries/list-commitments.query.js"
import type { listCommitmentsDueSoon as _listCommitmentsDueSoonDefinition } from "../../../features/commitments/queries/list-commitments-due-soon.query.js"
import type { listPeople as _listPeopleDefinition } from "../../../features/people/queries/list-people.query.js"
import type { listProjects as _listProjectsDefinition } from "../../../features/projects/queries/list-projects.query.js"

export const api = {
  actions: {
    createCommitment: createActionClient<Parameters<typeof _createCommitmentDefinition.run>[1], Awaited<ReturnType<typeof _createCommitmentDefinition.run>>>("createCommitment"),
    createPerson: createActionClient<Parameters<typeof _createPersonDefinition.run>[1], Awaited<ReturnType<typeof _createPersonDefinition.run>>>("createPerson"),
    createProject: createActionClient<Parameters<typeof _createProjectDefinition.run>[1], Awaited<ReturnType<typeof _createProjectDefinition.run>>>("createProject"),
  },
  queries: {
    listCommitments: createQueryClient<Parameters<typeof _listCommitmentsDefinition.run>[1], Awaited<ReturnType<typeof _listCommitmentsDefinition.run>>>("listCommitments"),
    listCommitmentsDueSoon: createQueryClient<Parameters<typeof _listCommitmentsDueSoonDefinition.run>[1], Awaited<ReturnType<typeof _listCommitmentsDueSoonDefinition.run>>>("listCommitmentsDueSoon"),
    listPeople: createQueryClient<Parameters<typeof _listPeopleDefinition.run>[1], Awaited<ReturnType<typeof _listPeopleDefinition.run>>>("listPeople"),
    listProjects: createQueryClient<Parameters<typeof _listProjectsDefinition.run>[1], Awaited<ReturnType<typeof _listProjectsDefinition.run>>>("listProjects"),
  }
} as const
