// GENERATED BY loomstack. DO NOT EDIT.

import { lazy } from "react"
import type { ComponentType, LazyExoticComponent } from "react"

export interface LoomStackRoute {
  id: string
  feature: string
  path: string
  component: LazyExoticComponent<ComponentType>
}

export const routes: LoomStackRoute[] = [
  { id: "commitments-list", feature: "commitments", path: "/commitments", component: lazy(() => import("../../../features/commitments/ui/commitments-list.view")) },
  { id: "people-list", feature: "people", path: "/people", component: lazy(() => import("../../../features/people/ui/people-list.view")) },
  { id: "projects-list", feature: "projects", path: "/projects", component: lazy(() => import("../../../features/projects/ui/projects-list.view")) },
]
