export function appTemplateFiles(appName: string): Record<string, string> {
  return {
    "package.json": `${JSON.stringify({
      name: appName,
      version: "0.1.0",
      private: true,
      type: "module",
      packageManager: "pnpm@11.11.0",
      scripts: {
        loom: "loom",
        dev: "pnpm --parallel --filter './apps/*' dev",
        generate: "loom generate",
        verify: "loom verify",
        test: "vitest run --passWithNoTests",
        typecheck: "tsc --noEmit",
        build: "pnpm generate && pnpm -r --filter './apps/*' build"
      },
      devDependencies: {
        "@loom/cli": "^0.1.0",
        "@loom/react": "^0.1.0",
        "@loom/runtime": "^0.1.0",
        "@loom/postgres": "^0.1.0",
        "@types/node": "^24.0.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        react: "^19.2.7",
        "react-dom": "^19.2.7",
        typescript: "^5.9.3",
        vitest: "^4.1.10"
      }
    }, null, 2)}\n`,
    "pnpm-workspace.yaml": "packages:\n  - apps/*\n\nallowBuilds:\n  esbuild: true\n",
    "tsconfig.json": `${JSON.stringify({
      compilerOptions: {
        target: "ES2023",
        module: "ESNext",
        moduleResolution: "Bundler",
        lib: ["ES2023", "DOM", "DOM.Iterable"],
        strict: true,
        noUncheckedIndexedAccess: true,
        exactOptionalPropertyTypes: true,
        esModuleInterop: true,
        skipLibCheck: true,
        resolveJsonModule: true,
        jsx: "react-jsx"
      },
      include: ["apps/**/*.ts", "apps/**/*.tsx", "features/**/*.ts", "features/**/*.tsx", "shared/**/*.ts", "loom.config.ts"]
    }, null, 2)}\n`,
    "vitest.config.ts": `import { defineConfig } from "vitest/config"\n\nexport default defineConfig({ test: { include: ["features/**/*.test.ts", "features/**/*.test.tsx"] } })\n`,
    "loom.config.ts": `import { defineLoomConfig } from "@loom/runtime"\n\nexport default defineLoomConfig({\n  appName: "${appName}",\n  packageManager: "pnpm",\n  frontend: "react",\n  backend: "koa",\n  database: "postgres",\n  featuresDir: "features",\n  generatedDir: ".loom"\n})\n`,
    "AGENTS.md": `# ${appName} agent instructions\n\nThis is a loom app. Humans define product intent; agents edit explicit feature contracts.\n\n## Architecture\n\n\`\`\`text\nReact = presentation\nKoa = transport\nfeatures/* = product behavior and source of truth\n\`\`\`\n\n## Canonical feature layout\n\n- \`feature.yaml\`: declared contract\n- \`model.schema.ts\`: entities\n- \`permissions.policy.ts\`: authorization policy\n- \`actions/*.action.ts\`: mutations\n- \`queries/*.query.ts\`: reads\n- \`ui/*.view.tsx\`: routes and presentation\n- \`tests/*.test.ts\`: behavior proof\n\n## Hard rules\n\n- Never edit files containing \`GENERATED BY loom\`.\n- Never put database access or raw fetch in feature UI.\n- Never import Koa in feature logic.\n- Keep action/query names synchronized with \`feature.yaml\`.\n- Run scoped verification after every feature change.\n\n## Agent workflow\n\n1. \`pnpm loom context feature <name> --json\`\n2. \`pnpm loom affected <file> --json\`\n3. Edit only canonical authored files.\n4. \`pnpm loom generate\`\n5. \`pnpm loom verify feature <name> --json\`\n6. \`pnpm test\`\n`,
    "CLAUDE.md": `# ${appName} loom memory\n\nProduct behavior lives in \`features/*\`. React renders; Koa transports. Read feature-local \`AGENTS.md\`, never edit generated files, use generated RPC clients, and finish with \`pnpm loom generate && pnpm loom verify --json\`.\n`,
    ".gitignore": "node_modules/\ndist/\ncoverage/\n.env\n.env.local\n.DS_Store\n",
    "features/.gitkeep": "",
    "apps/web/package.json": `${JSON.stringify({
      name: `@${appName}/web`,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: { dev: "vite", build: "vite build" },
      dependencies: {
        "@loom/react": "^0.1.0",
        "@loom/runtime": "^0.1.0",
        "@vitejs/plugin-react": "^6.0.3",
        react: "^19.2.7",
        "react-dom": "^19.2.7",
        vite: "^8.1.4"
      }
    }, null, 2)}\n`,
    "apps/web/index.html": `<!doctype html>\n<html lang="en">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>${appName}</title>\n  </head>\n  <body>\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"></script>\n  </body>\n</html>\n`,
    "apps/web/src/main.tsx": `import { StrictMode } from "react"\nimport { createRoot } from "react-dom/client"\nimport { App } from "./app.js"\n\nconst root = document.getElementById("root")\nif (!root) throw new Error("Missing #root element")\ncreateRoot(root).render(<StrictMode><App /></StrictMode>)\n`,
    "apps/web/src/app.tsx": `import { Suspense } from "react"\nimport { routes } from "./routes.generated.js"\n\nfunction matches(pattern: string, path: string) {\n  const expected = pattern.split("/").filter(Boolean)\n  const actual = path.split("/").filter(Boolean)\n  return expected.length === actual.length && expected.every((part, index) => part.startsWith(":") || part === actual[index])\n}\n\nexport function App() {\n  const route = routes.find((candidate) => matches(candidate.path, window.location.pathname))\n  if (!route) return <main><h1>Not found</h1></main>\n  const Component = route.component\n  return <Suspense fallback={<main>Loading…</main>}><Component /></Suspense>\n}\n`,
    "apps/web/vite.config.ts": `import { defineConfig } from "vite"\nimport react from "@vitejs/plugin-react"\n\nexport default defineConfig({\n  plugins: [react()],\n  server: { port: 3000, proxy: { "/_loom": "http://localhost:3001" } }\n})\n`,
    "apps/api/package.json": `${JSON.stringify({
      name: `@${appName}/api`,
      version: "0.1.0",
      private: true,
      type: "module",
      scripts: { dev: "tsx watch src/server.ts", build: "tsup src/server.ts --format esm --clean" },
      dependencies: {
        "@loom/koa": "^0.1.0",
        "@loom/runtime": "^0.1.0",
        "@loom/postgres": "^0.1.0",
        koa: "^3.2.1",
        "koa-bodyparser": "^4.4.1"
      },
      devDependencies: {
        "@types/koa": "^3.0.3",
        "@types/koa-bodyparser": "^4.3.13",
        tsup: "^8.5.0",
        tsx: "^4.20.0"
      }
    }, null, 2)}\n`,
    "apps/api/src/context.ts": `import type Koa from "koa"\nimport { PostgresDatabase } from "@loom/postgres"\n\nexport const db = new PostgresDatabase()\n\nexport async function createRequestContext(ctx: Koa.Context) {\n  const userId = ctx.get("x-user-id")\n  return {\n    requestId: ctx.get("x-request-id") || crypto.randomUUID(),\n    ...(userId ? { user: { id: userId } } : {}),\n    db,\n    logger: console\n  }\n}\n`,
    "apps/api/src/server.ts": `import Koa from "koa"\nimport bodyParser from "koa-bodyparser"\nimport { registerGeneratedRoutes } from "./routes.generated.js"\n\nconst app = new Koa()\napp.use(bodyParser())\nregisterGeneratedRoutes(app)\n\nconst port = Number(process.env.PORT ?? 3001)\napp.listen(port, () => console.log(\`loom API listening on http://localhost:\${port}\`))\n`
  }
}
