import { createHash } from "node:crypto"
import { existsSync, mkdirSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"

export const GENERATED_SOURCE_MARKER = "// GENERATED BY loomstack. DO NOT EDIT."

export function stableJson(value: unknown): string {
  return `${JSON.stringify(value, null, 2)}\n`
}

export function sha256(content: string): string {
  return createHash("sha256").update(content).digest("hex")
}

export function writeProjectFile(root: string, path: string, content: string, overwrite = true): void {
  const absolute = join(root, path)
  if (!overwrite && existsSync(absolute)) throw new Error(`Target already exists: ${path}`)
  mkdirSync(dirname(absolute), { recursive: true })
  writeFileSync(absolute, content, "utf8")
}
